#!/bin/bash
#
# Export XLIFF files translated by Weblate into an AtoM repository

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

usage() {
    echo "Exports XLIFF from the Weblate repository to AtoM."
    echo ""
    echo "$0"
    echo "    -h --help"
    echo "    --atom-dir=<path>"
    echo "    --weblate-dir=<path>"
    echo "    [--language=<language code>]"
    echo "    [--commit=<message>]"
    echo "    [--branch=<branch>]"
    echo "    [--no-push]"
    echo "    [--no-pull]"
    echo ""
    echo "The --commit will automatically commit and push any XLIFF changed"
    echo "    using the specified message, unless --no-pull is provided"
    echo
    echo "The --no-pull option skips optional git pulls."
}

# Parse command-line options
LANG_CODE="all"
NO_PULL=false
NO_PUSH=false
while [ "$1" != "" ]; do
    # Attempt to parse out value
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`

    # Handle when equal sign wasn't used to set option value
    if [ -n "$CURRENT_OPTION" ]; then
      VALUE=$PARAM
      PARAM=$CURRENT_OPTION
      unset CURRENT_OPTION
    fi

    # Process option
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        --atom-dir)
            ATOM_DIR=$VALUE
            ;;
        --weblate-dir)
            WEBLATE_DIR=$VALUE
            ;;
        --language)
            LANG_CODE=$VALUE
            ;;
        --branch)
            BRANCH=$VALUE
            ;;

        --commit)
            COMMIT_WITH_MESSAGE=${VALUE:=Imported XLIFF files from Weblate.}
            ;;
        --no-push)
            NO_PUSH=true
            VALUE=true
            ;;
        --no-pull)
            NO_PULL=true
            VALUE=true
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac

    # Handle null values
    if [ -z "$VALUE" ]; then
        CURRENT_OPTION=$PARAM
    fi

    shift
done

# Require specification of both the AtoM repo directory and the Weblate repo directory
if [ -z $ATOM_DIR ] || [ -z $WEBLATE_DIR ]; then
    usage
    exit 1
fi

# Note initial directory
INITIAL_DIRECTORY=`pwd`

# Get absolute path to AtoM dir and abort if directory doesn't exist
ATOM_DIR=`realpath $ATOM_DIR`
if [ ! -d $ATOM_DIR ] ; then
    echo "The AtoM directory specified doesn't exist."
    exit
fi

# Get absolute path to Weblate dir and abort if directory doesn't exist
WEBLATE_DIR=`realpath $WEBLATE_DIR`
if [ ! -d $WEBLATE_DIR ] ; then
    echo "The Weblate directory specified doesn't exist."
    exit
fi

# Change to AtoM directory, take note of branch, and guess version
cd $ATOM_DIR
ATOM_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
ATOM_VERSION=`basename $ATOM_BRANCH`
echo "Currently in the '$ATOM_BRANCH' branch of the AtoM repo..."

# Take note of Weblate repo's branch
cd $WEBLATE_DIR
WEBLATE_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
echo "Currently in the '$WEBLATE_BRANCH' branch of the Weblate repo..."
echo

# Exit if estimated AtoM version doesn't match name of Weblate branch
if [ "$ATOM_VERSION" != "$WEBLATE_BRANCH" ]; then
    echo "Estimated AtoM version (using basename of AtoM branch) is '$ATOM_VERSION' and doesn't match name of checked out Weblate branch."
    exit 1
fi

if [ "$NO_PULL" = false ]; then
    # Offer to update the Weblate repo
    while true; do
        read -p "Do you wish to 'git pull --rebase' to update the Weblate repo before exporting from it? " yn
        case $yn in
            [Yy]* ) git pull --rebase; echo; break;;
            [Nn]* ) echo; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done

    # Offer to update the AtoM repo
    cd $ATOM_DIR
    while true; do
        read -p "Do you wish to 'git pull --rebase' to update the AtoM repo before exporting to it? " yn
        case $yn in
            [Yy]* ) git pull --rebase; echo; break;;
            [Nn]* ) echo; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

# Compare AtoM XLIFF to Weblate XLIFF to see if an import is needed
$SCRIPT_DIR/scripts/compare $ATOM_DIR/apps/qubit/i18n $WEBLATE_DIR/i18n

# Import if Atom's not up to date
if [ $? -ne 0 ]
then

    # Export XLIFF to AtoM
    $SCRIPT_DIR/scripts/migrate --export --language="$LANG_CODE" --approved $WEBLATE_DIR/i18n $ATOM_DIR/apps/qubit/i18n

    # Offer to commit and push changes if XLIFF was imported successfully
    if [ $? -eq 0 ]
    then
        cd $ATOM_DIR

        echo

        if [ "$COMMIT" != false ]; then
          if [ x"$BRANCH" != "x" ]; then
             git stash save . 
             git checkout $BRANCH > /dev/null || git checkout -b $BRANCH
             git rebase qa/$ATOM_VERSION
             git stash pop --quiet
          fi
            git add apps/qubit/i18n
            git commit -m "$COMMIT_WITH_MESSAGE"
            if [ "$NO_PUSH" = false ]; then
               git push
            fi
        fi
    fi
else
    echo "No export needed."
fi

# Return to inital directory
cd $INITIAL_DIRECTORY
