#!/bin/bash
#
# Import AtoM XLIFF files into a reposity containing XLIFF files to be
# translated using Weblate

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

usage() {
    echo "Imports XLIFF from AtoM into a repository used by Weblate."
    echo ""
    echo "$0"
    echo "    -h --help"
    echo "    --atom-dir=<path>"
    echo "    --weblate-dir=<path>"
    echo "    [--language=<language code>]"
    echo "    [--commit-with-message=<message>]"
    echo "    [--no-pull]"
    echo "    [--no-push]"
    echo "    [--skip-version-check]"
    echo "    [--skip-push-translations]"
    echo ""
    echo "The --commit-with-message will automatically commit any XLIFF changed"
    echo "    using the specified message."
    echo
    echo "The --no-pull option skips optional git pulls."
    echo "The --no-push option skips optional git pulls."
}

# Parse command-line options
LANG_CODE="all"
COMMIT_WITH_MESSAGE=false
NO_PULL=false
NO_PUSH=false
ATOM_SOURCE_DIR=".tx/i18n"
SKIP_VERSION_CHECK=false
SKIP_PUSH_TRANSLATIONS=false
while [ "$1" != "" ]; do
    # Attempt to parse out value
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`

    # Handle when equal sign wasn't used to set option value
    if [ -n "$CURRENT_OPTION" ]; then
      VALUE=$PARAM
      PARAM=$CURRENT_OPTION
      unset CURRENT_OPTION
    fi

    # Process option
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        --atom-dir)
            ATOM_DIR=$VALUE
            ;;
        --weblate-dir)
            WEBLATE_DIR=$VALUE
            ;;
        --language)
            LANG_CODE=$VALUE
            ;;
        --commit-with-message)
            COMMIT_WITH_MESSAGE=$VALUE
            ;;
        --no-pull)
            NO_PULL=true
            VALUE=true
            ;;
        --no-push)
            NO_PUSH=true
            VALUE=true
            ;;
        --skip-version-check)
            SKIP_VERSION_CHECK=true
            VALUE=true
            ;;
        --skip-push-translations)
            SKIP_PUSH_TRANSLATIONS=true
            VALUE=true
            ;;
        --overwrite-weblate-xliff)
            OVERWRITE=true
            VALUE=true
            ;;
        --remove-translated-attribute)
            REMOVE_TRANSLATED=true
            VALUE=true
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac

    # Handle null values
    if [ -z "$VALUE" ]; then
        CURRENT_OPTION=$PARAM
    fi

    shift
done

# Require specification of both the AtoM repo directory and the Weblate repo directory
if [ -z $ATOM_DIR ] || [ -z $WEBLATE_DIR ]; then
    usage
    exit 1
fi

# Note initial directory
INITIAL_DIRECTORY=`pwd`

# Set default commit message (if .git/hooks/prepare-commit-msg is set to prepend it)
export GIT_COMMIT_PREPEND="Imported XLIFF files from AtoM."

# Get absolute path to AtoM dir and abort if directory doesn't exist
ATOM_DIR=`realpath $ATOM_DIR`
if [ ! -d $ATOM_DIR ] ; then
    echo "That AtoM directory doesn't exist."
    exit
fi

# Get absolute path to Weblate dir and abort if directory doesn't exist
WEBLATE_DIR=`realpath $WEBLATE_DIR`
if [ ! -d $WEBLATE_DIR ] ; then
    echo "The Weblate directory specified doesn't exist."
    exit
fi

# Take note of current branch checkout out by Weblate repo
cd $WEBLATE_DIR
WEBLATE_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`

# Change to AtoM directory, take note of branch, and guess version
cd $ATOM_DIR
ATOM_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
ATOM_VERSION=`basename $ATOM_BRANCH`

# Exit if estimated AtoM version doesn't match name of Weblate branch
if [ "$ATOM_VERSION" != "$WEBLATE_BRANCH" ] && [ "$SKIP_VERSION_CHECK" = false ]; then
    echo "Estimated AtoM version (using basename of AtoM branch) is '$ATOM_VERSION' and doesn't match name of checked out Weblate branch."
    exit 1
fi

# Change to AtoM directory and extract AtoM source strings,
echo "Extracting source strings from source code and adding them to AtoM XLIFF files..."
echo

# Extract AtoM and plugin translations and merge all into AtoM's .tx folder
if [ "$SKIP_PUSH_TRANSLATIONS" = false ]; then
    # This takes about .5 hours to run. If .tx already contains the combined XLIFF
    # required then this step can be skipped.
    phing i18n-push-translations
fi

# Display currently checked out Weblate and AtoM branches
echo "The Weblate repository has the '$WEBLATE_BRANCH' branch checked out."
echo "The AtoM repository has the '$ATOM_BRANCH' branch checked out."

# Change to Weblate directory and display currently checkout out Weblate branch
cd $WEBLATE_DIR

# Offer to update the Weblate repo
if [ "$NO_PULL" = false ]; then
    while true; do
        read -p "Do you wish to 'git pull --rebase' in the Weblate repository before importing? " yn
        case $yn in
            [Yy]* ) git pull --rebase; echo; break;;
            [Nn]* ) echo; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

# Compare AtoM XLIFF to Weblate XLIFF to see if an import is needed
$SCRIPT_DIR/scripts/compare --language="$LANG_CODE" $ATOM_DIR/$ATOM_SOURCE_DIR $WEBLATE_DIR/i18n

# Import if Weblate's not up to date
if [ $? -ne 0 ]
then

    MIGRATE_COMMAND="$SCRIPT_DIR/scripts/migrate"
    MIGRATE_OPTIONS=""

    if [ "$OVERWRITE" = true ]; then
        MIGRATE_OPTIONS="$MIGRATE_OPTIONS --overwrite"
    else
        MIGRATE_OPTIONS="$MIGRATE_OPTIONS --merge"
    fi

    if [ "$REMOVE_TRANSLATED" = true ]; then
        MIGRATE_OPTIONS="$MIGRATE_OPTIONS --remove-translated"
    fi

    MIGRATE_COMMAND="$MIGRATE_COMMAND $MIGRATE_OPTIONS --import --language="$LANG_CODE" $ATOM_DIR/$ATOM_SOURCE_DIR $WEBLATE_DIR/i18n"
    
    echo "$MIGRATE_COMMAND" 
    # Attempt import
    $MIGRATE_COMMAND

    MIGRATE_SUCCESS=$?

    # Check out AtoM i18n and plugins directory to remove changed local files
    cd $ATOM_DIR
    git checkout apps/qubit/i18n
    git checkout plugins
    cd $WEBLATE_DIR

    #######################################
    # Commit and push imported XLIFF files
    #######################################
    function commit_and_push {
        git add i18n
        git commit
        git push
    }

    # Offer to commit and push changes if XLIFF was imported successfully
    if [ $MIGRATE_SUCCESS -eq 0 ]; then
        echo

        if [ "$NO_PUSH" = false ]; then
            if [ "$COMMIT_WITH_MESSAGE" = false ]; then
                while true; do
                    read -p "Do you wish to commit the changes to the Weblate repo and push them? " yn
                    case $yn in
                        [Yy]* ) commit_and_push; break;;
                        [Nn]* ) exit;;
                        * ) echo "Please answer yes or no.";;
                    esac
                done
            else
                git add i18n
                git commit -m "$COMMIT_WITH_MESSAGE"
                git push
            fi
        fi
    fi

    echo
    echo "Remember to do a Git pull in the Weblate UI before doing translation work."
else
    echo "No import needed."
fi

# Return to inital directory
cd $INITIAL_DIRECTORY
