#!/bin/bash
#
# Import AtoM XLIFF files into a reposity containing XLIFF files to be
# translated using Weblate

usage() {
    echo "Imports XLIFF from AtoM into a repository used by Weblate."
    echo ""
    echo "$0"
    echo "\t-h --help"
    echo "\t--atom-dir=<path>"
    echo "\t--weblate-dir=<path>"
    echo ""
}

# Parse command-line options
while [ "$1" != "" ]; do
    # Attempt to parse out value
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`

    # Handle when equal sign wasn't used to set option value
    if [ -n "$CURRENT_OPTION" ]; then
      VALUE=$PARAM
      PARAM=$CURRENT_OPTION
      unset CURRENT_OPTION
    fi

    # Process option
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        --atom-dir)
            ATOM_DIR=$VALUE
            ;;
        --weblate-dir)
            WEBLATE_DIR=$VALUE
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac

    # Handle null values
    if [ -z $VALUE ]; then
        CURRENT_OPTION=$PARAM
    fi

    shift
done

# Require specification of both the AtoM repo directory and the Weblate repo directory
if [ -z $ATOM_DIR ] || [ -z $WEBLATE_DIR ]; then
    usage
    exit 1
fi

# Note initial directory
INITIAL_DIRECTORY=`cwd`

# Set default commit message (if .git/hooks/prepare-commit-msg is set to prepend it)
export GIT_COMMIT_PREPEND="Imported XLIFF files from AtoM."

# Get absolute path to AtoM dir and abort if directory doesn't exist
ATOM_DIR=`realpath $ATOM_DIR`
if [ ! -d $ATOM_DIR ] ; then
    echo "That AtoM directory doesn't exist."
    exit
fi

# Get absolute path to Weblate dir and abort if directory doesn't exist
WEBLATE_DIR=`realpath $WEBLATE_DIR`
if [ ! -d $WEBLATE_DIR ] ; then
    echo "The Weblate directory specified doesn't exist."
    exit
fi

# Take note of current branch checkout out by Weblate repo
cd $WEBLATE_DIR
WEBLATE_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`

# Change to AtoM directory, take note of branch, and guess version
cd $ATOM_DIR
ATOM_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
ATOM_VERSION=`basename $ATOM_BRANCH`

# Exit if estimated AtoM version doesn't match name of Weblate branch
if [ "$ATOM_VERSION" != "$WEBLATE_BRANCH" ]; then
    echo "Estimated AtoM version (using basename of AtoM branch) is '$ATOM_VERSION' and doesn't match name of checked out Weblate branch."
    exit 1
fi

# Change to AtoM directory and extract AtoM source strings,
echo "Extracting source strings from source code and adding them to AtoM XLIFF files..."
echo
phing i18n-extract

# Display currently checked out Weblate and AtoM branches
echo "The Weblate repository has the '$WEBLATE_BRANCH' branch checked out."
echo "The AtoM repository has the '$ATOM_BRANCH' branch checked out."

# Change to Weblate directory and display currently checkout out Weblate branch
cd $WEBLATE_DIR

# Offer to update the Weblate repo
while true; do
    read -p "Do you wish to 'git pull --rebase' in the Weblate repository before importing? " yn
    case $yn in
        [Yy]* ) git pull --rebase; echo; break;;
        [Nn]* ) echo; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Attempt import
./scripts/migrate --import $ATOM_DIR/apps/qubit/i18n i18n

# Check out AtoM i18n directory to remove changed local files
cd $ATOM_DIR
git checkout apps/qubit/i18n
cd $WEBLATE_DIR

#######################################
# Commit and push imported XLIFF files
#######################################
function commit_and_push {
    git add i18n
    git commit
    git push
}

# Offer to commit and push changes if XLIFF was imported successfully
if [ $? -eq 0 ]
then
    echo
    while true; do
        read -p "Do you wish to commit the changes to the Weblate repo and push them? " yn
        case $yn in
            [Yy]* ) commit_and_push; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

# Return to inital directory
cd $INITIAL_DIRECTORY

echo
echo "Remember to do a Git pull in the Weblate UI before doing translation work."
