#!/usr/bin/php
<?php

include('include/helpers.inc.php');

function blankXliffFileElementDateAttribute($file)
{
  $xml = simplexml_load_file($file);

  $elements = $xml->xpath("/xliff/file");

  foreach ($elements as $element)
  { 
    $element['date'] = '';
  }

  $xml->asXml($file);
}

function compare($fromI18nDir, $toI18nDir, $options = array())
{
  // Make sure destination directory exists
  if (!is_dir($toI18nDir))
  { 
    abort('No "'. $toI18nDir .'" directory.');
  }

  // Cycle through each AtoM language directory
  print "Attempting to cycle through language directories in ". $fromI18nDir ."...\n";
  try
  {
    $dir = new DirectoryIterator($fromI18nDir);
  }
  catch(Exception $e)
  {
    abort('Unable to access '. $fromI18nDir);
  }

  $compareCount = 0;

  foreach ($dir as $fileinfo)
  {
    if (!$fileinfo->isDot()) {
      $langDir = $fileinfo->getFilename();

      // There's no need to migrate English as it doesn't need to be translated
      if (is_dir($fromI18nDir . DIRECTORY_SEPARATOR . $langDir) && $langDir != 'en')
      {
        // Each language's XLIFF file'll end up in a subdir of the i18n directory
        $destLangDir = $toI18nDir . DIRECTORY_SEPARATOR . $langDir;

        // Create destination language directory if it doesn't exist
        if (!is_dir($destLangDir))
        {
          print "Compare could not complete: directory not found: ". $destLangDir ."\n";
          return false;
        }

        // Copy AtoM's XLIFF file to temp file, reformatting it to Weblate
        $langFileRelativePath = $langDir . DIRECTORY_SEPARATOR . "messages.xml";
        $fromFile = $fromI18nDir . DIRECTORY_SEPARATOR . $langFileRelativePath;
        $fromTmpFile = tempnam(sys_get_temp_dir(), 'xliffcomparefrom');
        copy($fromFile, $fromTmpFile);
        formatXliffForWeblate($fromTmpFile);
        blankXliffFileElementDateAttribute($fromTmpFile);
        unsetTransUnitAttributes($fromTmpFile);

        // Copy Weblate's XLIFF file to temp file
        $toFile = $toI18nDir . DIRECTORY_SEPARATOR . $langFileRelativePath;
        $toTmpFile = tempnam(sys_get_temp_dir(), 'xliffcompareto');
        copy($toFile, $toTmpFile);
        blankXliffFileElementDateAttribute($toTmpFile);
        unsetTransUnitAttributes($toTmpFile);

        if (!empty($options['debug']))
        {
          print 'DEBUG: Normalized and compared '. $fromFile .' ('. filesize($fromTmpFile) .' bytes) to '. $toFile .' ('. filesize($toTmpFile) ." bytes)\n";
        }

        if (sha1_file($fromTmpFile) != sha1_file($toTmpFile))
        {
          return false;
        }

        unlink($fromTmpFile);
        unlink($toTmpFile);

        $compareCount++;
      }
    }
  }

  return $compareCount;
}

$parsed = parseArgs($argv);
$args = $parsed['args'];
$flags = $parsed['flags'];

$atomDirectory = (isset($args[0])) ? $args[0] : null;
$weblateDirectory   = (isset($args[1])) ? $args[1] : null;

if (empty($atomDirectory) || empty($weblateDirectory))
{
  abort("Usage: ". basename(__FILE__) . " <AtoM i18n directory> <Weblate i18n directory>\n");
}

$compareCount = compare($atomDirectory, $weblateDirectory, $flags);

if ($compareCount)
{
  print "Done: compared ". $compareCount ." XLIFF files.\n";
}
else
{
  print "Compare failed.\n";
  exit(1);
}
